name: 'Setup, Restore, and Build Solution'
description: 'Checks out code, sets up .NET, restores NuGet packages, and builds the solution for CI jobs.'
runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: ./global.json

    - name: NuGet Restore
      shell: pwsh
      run: dotnet restore

    - name: Build
      shell: pwsh
      run: dotnet build --no-restore --configuration Release /p:Deterministic=true /p:UseSharedCompilation=false /p:BuildInParallel=false /nodeReuse:false /bl:./artifacts/logs/release/build.release.binlog
