# Serena project configuration for moq.analyzers
# C# Roslyn analyzer project for the Moq framework

# Languages for which language servers are started.
# csharp requires the presence of a .sln file in the project folder.
languages:
- csharp
- markdown
- yaml
- bash

# the encoding used by text files in the project
# For a list of possible encodings, see https://docs.python.org/3.11/library/codecs.html#standard-encodings
encoding: "utf-8"

# whether to use the project's gitignore file to ignore files
ignore_all_files_in_gitignore: true

# list of additional paths to ignore
ignored_paths:
- "**/bin/**"
- "**/obj/**"
- "**/artifacts/**"
- "**/.vs/**"
- "**/BenchmarkDotNet.Artifacts/**"
- "**/TestResults/**"

# whether the project is in read-only mode
# If set to true, all editing tools will be disabled and attempts to use them will result in an error
# Added on 2025-04-18
read_only: false

# list of tool names to exclude
excluded_tools: []

# initial prompt for the project
initial_prompt: "This is a Roslyn analyzer project for the Moq mocking framework.
  The solution file is Moq.Analyzers.sln. Key directories: src/Analyzers/ (analyzers),
  src/CodeFixes/ (code fixes), src/Common/ (shared logic), tests/Moq.Analyzers.Test/
  (tests). Always use symbol-based detection over string matching."

# project name
project_name: "moq-analyzers"

# list of tools to include that would otherwise be disabled
included_optional_tools: []

# fixed set of tools to use as the base tool set (if non-empty), replacing Serena's default set of tools.
# This cannot be combined with non-empty excluded_tools or included_optional_tools.
fixed_tools: []

# list of mode names to that are always to be included in the set of active modes
# The full set of modes to be activated is base_modes + default_modes.
# If the setting is undefined, the base_modes from the global configuration (serena_config.yml) apply.
# Otherwise, this setting overrides the global configuration.
# Set this to [] to disable base modes for this project.
# Set this to a list of mode names to always include the respective modes for this project.
base_modes:

# list of mode names that are to be activated by default.
# The full set of modes to be activated is base_modes + default_modes.
# If the setting is undefined, the default_modes from the global configuration (serena_config.yml) apply.
# Otherwise, this overrides the setting from the global configuration (serena_config.yml).
# This setting can, in turn, be overridden by CLI parameters (--mode).
default_modes:

# time budget (seconds) per tool call for the retrieval of additional symbol information
# such as docstrings or parameter information.
# This overrides the corresponding setting in the global configuration; see the documentation there.
# If null or missing, use the setting from the global configuration.
symbol_info_budget:

# The language backend to use for this project.
# If not set, the global setting from serena_config.yml is used.
# Valid values: LSP, JetBrains
# Note: the backend is fixed at startup. If a project with a different backend
# is activated post-init, an error will be returned.
language_backend:

# Unused optional keys removed for clarity.
# See the ai-agents/.serena/project.yml reference for all available options:
#   base_modes, default_modes, fixed_tools, symbol_info_budget, language_backend
