name: Auto-Approve and Auto-Merge Renovate PR
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate-approve-and-merge:
    runs-on: ubuntu-24.04-arm
    if: github.actor == 'renovate[bot]'
    steps:
      - name: Approve Renovate PR
        run: gh pr review --approve "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.GH_ACTIONS_PR_WRITE }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: Enable Auto-Merge and Squash
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.GH_ACTIONS_PR_WRITE }}
          PR_URL: ${{ github.event.pull_request.html_url }}
