name: "Label Previous Pull Requests"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 1"

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-24.04-arm
    steps:
    
    # Label PRs
    - uses: actions/labeler@v6
      with:        
        pr-number: |
          52
          57
          59
          60
          61
          63
          65
          66
          69
          70
          71
          73
          74
          76
          77
          79
          80
          81
          82
          83
          84
          86
          87
          88
          89
          91
          92
          93
          94
          99
          101
          102
          105
          106
          108
          113
          114
