name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - edited

permissions:
  contents: read

jobs:
  update_release_draft:
    name: Draft release notes
    if: github.event_name == 'push'
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
    steps:
      - name: Update release draft
        uses: release-drafter/release-drafter@139054aeaa9adc52ab36ddf67437541f039b88e2 # v7.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  label_pull_request:
    name: Label pull request
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Apply release-drafter labels
        uses: release-drafter/release-drafter@139054aeaa9adc52ab36ddf67437541f039b88e2 # v7.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
